### PR TITLE
Sending chat messages for full self disclosure using the Recall.ai API and a Zoom bot

### PR DESCRIPTION
**Pull request by BrennanJones**
Note that the following environment variables need to be set for this to work:

- `RECALL_API_KEY`: The API key for Recall.ai
- `RECALL_AI_API_BASE_URL`: The base URL for the Recall.ai API. If this is not set, then the default value is "https://us-west-2.recall.ai/api/v1".
- `ZOOM_CHATBOT_TIMEOUT`: A timeout for how long the Zoom bot will stay in the meeting after it is created (in seconds). If this is not set, then the default value is 180 seconds, or 3 minutes. This is to minimize the cost of using the Recall.ai API (as every second a bot spends in a meeting costs some money).

Also need to modify the settings of the Zoom app so that:

- The Zoom Meeting SDK is enabled, and
- The following API functions in the Zoom Apps SDK are enabled: `getMeetingJoinUrl` and `getMeetingUUID`.

### CODE REVIEW

**Comment by Shaomei** [comment]
Thanks @BrennanJones for working on this! Can you take a look at the unit tests and make sure they pass?

**Comment by BrennanJones** [comment]
> Thanks @BrennanJones for working on this! Can you take a look at the unit tests and make sure they pass?

It looks like the reason why the `nameTagForm.test.tsx` unit test is failing is because I added a new checkbox for "Send Disclosure Message". The unit test seems to be trying to fetch just one checkbox in the NameTagForm (lines 32 and 47 of `nameTagForm.test.tsx`), but throws an error when it detects that there are now multiple checkboxes.

I'll modify the unit test to fetch and test both checkboxes.

**Comment by BrennanJones** [comment]
I realized that currently this feature will only work if the user is a host or co-host in the meeting, since the `getMeetingJoinUrl` method that is called from the `sendChatMessage` function (in `zoomapi.ts`, line 39) requires the user to be a meeting host or co-host. The Recall.ai API needs the meeting URL (including the meeting ID and password) in order to create a bot that joins the meeting. If we want to get the meeting password without the user being a host or co-host, then we need to get this through some other means (we might be able to do this using the server-side REST API: https://devforum.zoom.us/t/get-meeting-passcode-using-zoom-app-sdk/85542/2).

There is also the limitation that the meeting itself needs to have chat enabled (not all Zoom meetings have chat enabled). Plus, if the waiting room is enabled, the bot will enter the waiting room before joining the call, and a host/co-host will need to admit the bot. Right now, the bot is configured to leave the waiting room (and the call) automatically if it reaches its timeout (`ZOOM_CHATBOT_TIMEOUT`) without being admitted.

**Review by Shaomei — APPROVED** [review]
Let's land it for now, we can revisit with a more comprehensive solution later.

**Pull request merged**
